name: Build and deploy Github pages
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name : Install Python dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Build Sphinx Doc
        working-directory: ./docs
        run: |
          sphinx-build -M html ./source ./build -Ea

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # branch on which files are commited
          folder: ./docs/build/html # The folder the action should deploy.
